import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { AIVideoGenerationProvider } from "./AIVideoGenerationProvider.js";
import type {
  AIProviderId,
  AIProviderRuntimeConfig,
} from "../types.js";
import type {
  AIVideoGenerationRequest,
  AIVideoGenerationResponse,
} from "../videoTypes.js";

const now = () => new Date().toISOString();

const createId = (prefix: string) =>
  `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;

const providerDirectory = dirname(fileURLToPath(import.meta.url));

const fixtureCandidateDirectories = [
  resolve(providerDirectory, "../fixtures"),
  resolve(providerDirectory, "../../../src/ai/fixtures"),
];

const readFixtureAsDataUrl = async (fileName: string, mimeType: string) => {
  for (const directory of fixtureCandidateDirectories) {
    try {
      const fileBuffer = await readFile(resolve(directory, fileName));
      return `data:${mimeType};base64,${fileBuffer.toString("base64")}`;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
        throw error;
      }
    }
  }

  throw new Error(`Mock video fixture is missing: ${fileName}`);
};

interface MockStoredVideoGeneration {
  response: AIVideoGenerationResponse;
  pollCount: number;
}

export class MockAIVideoGenerationProvider implements AIVideoGenerationProvider {
  readonly providerId: AIProviderId = "mock";

  readonly displayName = "Backend Mock Video Generation Provider";

  private generations = new Map<string, MockStoredVideoGeneration>();

  constructor(private readonly config?: AIProviderRuntimeConfig) {
    void this.config;
  }

  async generateVideo(
    request: AIVideoGenerationRequest,
  ): Promise<AIVideoGenerationResponse> {
    const timestamp = now();
    const generationId = createId("video_generation");
    const response: AIVideoGenerationResponse = {
      generationId,
      providerId: this.providerId,
      blockId: request.blockId,
      status: "queued",
      createdAt: timestamp,
      updatedAt: timestamp,
      progress: 8,
      videos: [],
      warnings: [
        "This video was generated by the backend mock video provider.",
      ],
    };

    this.generations.set(generationId, {
      response,
      pollCount: 0,
    });

    return response;
  }

  async getVideoGenerationResult(
    generationId: string,
  ): Promise<AIVideoGenerationResponse> {
    const stored = this.generations.get(generationId);

    if (!stored) {
      throw new Error(`Mock video generation not found: ${generationId}`);
    }

    stored.pollCount += 1;

    if (stored.pollCount === 1) {
      stored.response = {
        ...stored.response,
        status: "running",
        progress: 58,
        updatedAt: now(),
      };
      this.generations.set(generationId, stored);
      return stored.response;
    }

    if (stored.response.status !== "completed") {
      const [videoUrl, posterUrl] = await Promise.all([
        readFixtureAsDataUrl("mock-video.mp4", "video/mp4"),
        readFixtureAsDataUrl("mock-video-poster.png", "image/png"),
      ]);

      stored.response = {
        ...stored.response,
        status: "completed",
        progress: 100,
        updatedAt: now(),
        videos: [
          {
            assetId: createId("video_asset"),
            url: videoUrl,
            mimeType: "video/mp4",
            width: 320,
            height: 180,
            durationMs: 1000,
            posterAssetId: createId("poster_asset"),
            posterUrl,
            posterMimeType: "image/png",
            previewImageAssetId: createId("preview_asset"),
            previewImageUrl: posterUrl,
            previewImageMimeType: "image/png",
            providerMetadata: {
              source: "backend-mock-video-provider",
              durationSeconds: 1,
            },
          },
        ],
      };
      this.generations.set(generationId, stored);
    }

    return stored.response;
  }

  async cancelVideoGeneration(generationId: string): Promise<void> {
    const stored = this.generations.get(generationId);

    if (!stored) {
      return;
    }

    stored.response = {
      ...stored.response,
      status: "cancelled",
      updatedAt: now(),
    };

    this.generations.set(generationId, stored);
  }
}
